### ISSUE TITLE
can i log sql query with single request log?

### ISSUE THREAD

**Issue by DannyGokey** [wwwlicious/servicestack-seq-requestlogsfeature#18]
Hi,
can i log sql query into request log?(via ServiceStack OrmLiteExecFilter)

i think queryFilter are not in one scope(context) with request.

can't find a way do this, can you help?

**Comment by wwwlicious** [comment]
@DannyGokey you would probably have to write a custom implementation of the [logger](https://github.com/wwwlicious/servicestack-seq-requestlogsfeature/blob/master/src/ServiceStack.Seq.RequestLogsFeature/SeqRequestLogsFeature.cs#L153) as there is nothing built in for this.
