### ISSUE TITLE
Version v4.0.86 is no more compatible with ServiceStack.Server v5.1

### ISSUE THREAD

**Issue by labilbe** [wwwlicious/servicestack-seq-requestlogsfeature#19]
Hi,

I can't upgrade ServiceStack.Server to version 5.1 because ServiceStack.Seq.RequestLogsFeature v4.0.86 has the following constraint 

> constraint: ServiceStack.Server (>= 4.5.14 && < 5.1.0)'.

Can you please update the version so the update can be done?

Thank you.

**Comment by wwwlicious** [comment]
#20 resolves this
