### ISSUE TITLE
ServiceStack V3 SEQ server version.

### ISSUE THREAD

**Issue by mtsvietukhin** [wwwlicious/servicestack-seq-requestlogsfeature#23]
Hello I have old v3 ServiceStack

I got nuget 3.0.26 what server version I need to download?

**Comment by wwwlicious** [comment]
For seq you can download the latest release if you plan to run it on > Windows 7. 
The Seq 4.x versions will work on older OS's

**Comment by mtsvietukhin** [comment]
Thanks for the quick response. I have ServiceStack v3.9.71 and installed latest SEQ. tried with multiple versions.  I added this line to Host Plugins.Add(new SeqRequestLogsFeature("http://localhost:5341"));

Do I need to do anything else in order this to work?

**Comment by wwwlicious** [comment]
No that should be all that is required. 
The plugin creates json from the requests and sends it to the seq ingestion url both of which haven't had breaking changes since Seq version 3 IIRC. 

The seq server should not force SSL if you are using the url above and it should also not require ApiKey's for all logged events. You'll find this in the Seq admin UI.

**Comment by wwwlicious** [comment]
The plugin registers an instance of `IRequestLogger` in the container.

Using that instance, you can call the Log method directly.

https://github.com/wwwlicious/servicestack-seq-requestlogsfeature/blob/v3/src/ServiceStack.Seq.RequestLogsFeature/SeqRequestLogger.cs#L48

**Comment by mtsvietukhin** [comment]
![image](https://user-images.githubusercontent.com/31663234/51761962-4744b300-2083-11e9-812d-c48735fda7c2.png)

**Comment by mtsvietukhin** [comment]
That was due to our property ServiceStack.Text.JsConfig.EmitCamelCaseNames = true;

**Comment by mtsvietukhin** [comment]
Here is my fix in case you want to update your V3 library: 
I have to switch to use https://www.newtonsoft.com/json and HttpClient
instead for ServiceStack.Text.Json
Task.Run(async () =>
      {
        var client = new HttpClient();
        client.DefaultRequestHeaders.Add("X-Seq-ApiKey", apiKey);
        var requestBody = JsonConvert.SerializeObject(new { events = new SeqRequestLogEntry[1]{ requestLogEntry } }, new JsonSerializerSettings
        {
          ContractResolver = new DefaultContractResolver()
        });
        var httpRequestMessage = new HttpRequestMessage(new HttpMethod("POST"), $"{seqUrl}/api/events/raw")
        {
          Content = new StringContent(requestBody, Encoding.UTF8, "application/json")
        };
        await client.SendAsync(httpRequestMessage);
      });
    }

**Comment by wwwlicious** [comment]
newer versions use JSConfig scopes. v3 doesn't have scopes and that branch is not maintained. Glad you were able to get it working. 👍 

https://github.com/wwwlicious/servicestack-seq-requestlogsfeature/blob/master/src/ServiceStack.Seq.RequestLogsFeature/SeqRequestLogger.cs#L35
