### ISSUE TITLE
Question:  How can I add an enricher to your plugin?

### ISSUE THREAD

**Issue by VagyokC4** [wwwlicious/servicestack-seq-requestlogsfeature#25]
I'm using your plugin for Request Logging, however, I would like to bootstrap an enricher to your registration.  Is this possible?

**Comment by wwwlicious** [comment]
The plugin doesn't use Serilog so doesn't have the enricher concept. 
You can use the following [delegate](https://github.com/wwwlicious/servicestack-seq-requestlogsfeature/blob/develop/src/ServiceStack.Seq.RequestLogsFeature/SeqRequestLogsFeature.cs#L166) however to intercept and modify any logging events
